### ISSUE TITLE
Fix Next js prerender Error at page "/"

### ISSUE THREAD

**Issue by akadeepesh** [akadeepesh/Simplicity#8]
I'm getting this error while building app `npm run build`

`Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error`

**Comment by Rahulagg13** [comment]
Hey, 
I'd love to work on this issue. Could you please assign it to me? I'll start working on it right away!

**Comment by akadeepesh** [comment]
yeah sure @Rahulagg13 Go on, assigned.

**Comment by akadeepesh** [comment]
@Rahulagg13 consider pulling from main I've wrapped the app around clerk provider as It was removed by security bots maybe.

**Comment by Rahulagg13** [comment]
hey , I wanted to ask if you could provide more details about when exactly the issue occurs during the build process. I’ve tested the build on my local machine, and everything works fine.

**Comment by akadeepesh** [comment]
My bad :) after wrapping the app around clerk provider the issue is not there anymore, closing this issue now.
